// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3550.RbtxStrongTaupe2016.subsystems;

import java.util.Date;

import org.usfirst.frc3550.RbtxStrongTaupe2016.RobotMap;
import org.usfirst.frc3550.RbtxStrongTaupe2016.commands.*;
import org.usfirst.frc3550.RbtxStrongTaupe2016.filtering.LowPassFilter;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;



/**
 * The RbtxAccelerateurSubsystem incorporates the sensors and actuators attached to
 * the robots shooter. These include only one motor.
 */
public class RbtxShooterSubsystem extends Subsystem {

	
	private SpeedController m_moteur = RobotMap.moteurAccelerateur;
	
	private Encoder m_encodeurShooter = RobotMap.encodeurShooter; //to validate
	
	
	
	private static final double VITESSE_MAXIMALE = 1;
	private static final double VITESSE_90 = 0.9;
	private static final double VITESSE_80 = 0.8;
	private static final double VITESSE_70 = 0.7;
	private static final double VITESSE_MINIMALE = 0.75;
	private static final double VITESSE_ZERO = 0;
	
	
	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	public void initDefaultCommand() {
		
		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand()); // To remove once we have a constant value
		//setDefaultCommand(new RbtxAccelerPourLancerManuelleCommand());
	}
	
	
	/**
	 * La methode accelerVitesseMaximale permet de mettre le shooter a une vitesse optimale en vue d un tir.
	 * La vitesse est predefinie.
	 *
	 * @param Aucun argument
	 */
	public void accelererVitesseMaximale() {
			m_moteur.set(VITESSE_MAXIMALE);
	}
	
	public void accelererVitesse90() {
		m_moteur.set(VITESSE_90);
	}
	
	public void accelererVitesse80() {
		m_moteur.set(VITESSE_80);
	}
	
	public void accelererVitesse70() {
		m_moteur.set(VITESSE_70);
	}
	
	
	/**
	 * La methode accelerVitesseManuelle permet de mettre le shooter a une vitesse optimale d un tir.
	 * a laide du throtlle du joystick
	 *
	 * @param valeur lue du throttle du copilote
	 */
	public void accelererVitesseManuelle(double vitesse){
		//double vitesse = ThrottleValue;
		//if (vitesse < 0){
			//vitesse = 0;
			//}
			m_moteur.set(vitesse);
	}

	/**
	 * La methode accelerVitesseMinimale permet de mettre le shooter a une vitesse minimale.
	 * La vitesse est predefinie.
	 *
	 * @param Aucun argument
	 */
	public void preparerVitesseMinimale(){
		m_moteur.set(VITESSE_MINIMALE);
	}
	
	/**
   	 * La methode getCurrentShooterSpeed returne la valeur actuelle de la vitesse du moteur du shooter 
   	 * Cette methode est utilisee par la commande RbtxShooterMaxSpeedPIDCommand
   	 * @
   	 * @param Aucun argument
   	 */
       public double getCurrentShooterSpeed() {
       	return m_moteur.get();
       }
       
       /**
      	 * La methode setCurrentShooterSpeed met la vitesse du shooter a une valeur desiree
      	 * Cette methode est utilisee par la commande RbtxShooterMaxSpeedPIDCommand
      	 * @
      	 * @param ShooterPIDSpeed
      	 */
          public void setShooterRPM(double ShooterPIDSpeed) {
          	m_moteur.set(ShooterPIDSpeed);
          	
          }

	/**
	 * La methode stop permet d arreter le moteur du shooter.
	 * La vitesse est predefinie.
	 *
	 * @param Aucun argument
	 */
	public void stop(){
		m_moteur.set(VITESSE_ZERO);
	}
	
	/**
	 * @return Whether or not the shooter is ready to shoot.
	 */
	public boolean accelererateurPret(){
		return (m_moteur.get() >= VITESSE_MAXIMALE);
	}

	public double getEncoderShooterRPM() {
		// TODO Auto-generated method stub
		return m_encodeurShooter.get();
	}

	public void resetEncodeurShooter() {
		// TODO Auto-generated method stub
		m_encodeurShooter.reset();
		
	}
}

